### ISSUE TITLE
Does not handle local letters correctly

### ISSUE THREAD

**Issue by saebod** [microsoft/fabric-cicd#129]
### Library Version

0.1.6

### What is the problem?

When using the package to publish code, it does not handle local letters correctly. In Denmark, we have the letters "æ", "ø", and "å". If my code includes these letters, the output changes when published to Fabric. For example, I have a SELECT statement that includes the column "Bopælsadresse" in a notebook. When I publish this using the package, it changes "Bopælsadresse" to "BopÃ¦lsadresse". This problem does not occur when using the REST API directly; it only happens with the package.

### Is there an ideal solution?

That it does not change the letters and publish the code as it is. eg let it handle "utf-8"

**Comment by saebod** [comment]
I have tested the previous version 0.1.5, where this bug does not exist. Therefore, the bug was introduced in the current version

**Comment by saebod** [comment]
version 0.1.6 

![Image](https://github.com/user-attachments/assets/8001e6b2-19b7-4f6e-93f1-237f9b08306f)

version 0.1.5

![Image](https://github.com/user-attachments/assets/69772ba4-9978-4c26-8a77-222c05330eb2)

**Comment by jmuziki** [comment]
@saebod Thanks for raising, this has been resolved in v0.1.7 which has just been shipped.

**Comment by j-heinze** [comment]
@jmuziki It does not seem to be fully resolved. I still get the problem for reports and semantic models:

![Image](https://github.com/user-attachments/assets/deb3f875-eef3-45c5-8ba8-ead0f5c5e00f)
example .platform for a semantic model:

`{
    "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
    "metadata": {
        "type": "SemanticModel",
        "displayName": "ABCÄÖÜTÄTÜTÖ"
    },
    "config": {
        "version": "2.0",
        "logicalId": "5ead2a08-6831-80df-4110-6265e29e3ee7"
    }
}`

Seems to be an error in the items - updateDefinition endpoint of the fabric api or the powerbi service, because the base64 content of the api request seems to be encoding fine:
`{
                "path": ".platform",
                "payload": "ewogICAgIiRzY2hlbWEiOiAiaHR0cHM6Ly9kZXZlbG9wZXIubWljcm9zb2Z0LmNvbS9qc29uLXNjaGVtYXMvZmFicmljL2dpdEludGVncmF0aW9uL3BsYXRmb3JtUHJvcGVydGllcy8yLjAuMC9zY2hlbWEuanNvbiIsCiAgICAibWV0YWRhdGEiOiB7CiAgICAgICAgInR5cGUiOiAiU2VtYW50aWNNb2RlbCIsCiAgICAgICAgImRpc3BsYXlOYW1lIjogIkFCQ8OEw5bDnFTDhFTDnFTDliIKICAgIH0sCiAgICAiY29uZmlnIjogewogICAgICAgICJ2ZXJzaW9uIjogIjIuMCIsCiAgICAgICAgImxvZ2ljYWxJZCI6ICI1ZWFkMmEwOC02ODMxLTgwZGYtNDExMC02MjY1ZTI5ZTNlZTciCiAgICB9Cn0K",
                "payloadType": "InlineBase64"
            }`
